//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EY.ATF.Tool.Services.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [DataContract]
    public class CopyHubModel
    {
        public CopyHubModel()
        {
            Data = new CopyHubModelData();
            Collections = new CopyHubModelCollections();
        }

        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "data")]
        public CopyHubModelData Data { get; set; }

        [DataMember(Name = "collections")]
        public CopyHubModelCollections Collections { get; set; }
    }

    [DataContract]
    public class CopyHubModelData
    {
        public CopyHubModelData()
        {
            this.CopyRequestReceiver = new CopyRequestUser();
        }

        [DataMember(Name = "copyrequestreceiver")]
        public CopyRequestUser CopyRequestReceiver { get; set; }

        [DataMember(Name = "copyname")]
        public string CopyName { get; set; }
    }

    [DataContract]
    public class CopyHubModelCollections
    {
        public CopyHubModelCollections()
        {
            this.CopyObjects = new List<CopyObjectModel>();
        }

        [DataMember(Name = "copyobjects")]
        public List<CopyObjectModel> CopyObjects { get; set; }
    }

    [DataContract]
    public class CopyObjectModel
    {
        [DataMember(Name = "id")]
        public int Id { get; set; }

        [DataMember(Name = "data")]
        public CopyObjectModelData Data { get; set; }

        [DataMember(Name = "collections")]
        public CopyObjectModelCollections Collections { get; set; }
    }

    [DataContract]
    public class CopyObjectModelCollections
    {
        public CopyObjectModelCollections()
        {
            this.ChildNodes = new List<CopyObjectModel>();
        }

        [DataMember(Name = "childNodes")]
        public List<CopyObjectModel> ChildNodes { get; set; }

    }

    [DataContract]
    public class CopyObjectModelData
    {
        [DataMember(Name = "copyobjectids")]
        public List<int> CopyObjectIds { get; set; }

        [DataMember(Name = "label")]
        public string Label { get; set; }

        [DataMember(Name = "title")]
        public string Title { get; set; }

        [DataMember(Name = "isRequired")]
        public bool IsRequired { get; set; }

        [DataMember(Name = "isSelected")]
        public bool IsSelected { get; set; }

        [DataMember(Name = "isgroupofcopyobjects")]
        public bool IsGroupOfCopyObjects { get; set; }

        [DataMember(Name = "copyobjectgrouptypeid")]
        public int CopyObjectGroupTypeId { get; set; }

    }

    [DataContract]
    public class CopyMetadataModel
    {
        public CopyMetadataModel()
        {
            this.Data = new CopyMetadataModelData();
        }
        [DataMember(Name = "data")]
        public CopyMetadataModelData Data { get; set; }
    }

    [DataContract]
    public class CopyMetadataModelData
    {
        public CopyMetadataModelData()
        {
            this.CopyRequestReceiver = new CopyRequestUser();
        }

        [DataMember(Name = "copyrequestreceiver")]
        public CopyRequestUser CopyRequestReceiver { get; set; }


    }

    [DataContract]
    public class CopyRequestUser
    {
        public CopyRequestUser()
        {
            this.Data = new CopyRequestUserData();
        }
        [DataMember(Name = "data")]
        public CopyRequestUserData Data { get; set; }
    }

    [DataContract]
    public class CopyRequestUserData
    {
        [DataMember(Name = "email")]
        public string Email { get; set; }

        [DataMember(Name = "gui")]
        public string UserGUI { get; set; }
    }

}